# Generated by Django 4.2.26 on 2025-11-12 21:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_household_digest',
            field=models.BooleanField(default=False, verbose_name='Ежедневная сводка'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_invitation',
            field=models.BooleanField(default=True, verbose_name='Письмо о приглашениях'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_new_task',
            field=models.BooleanField(default=True, verbose_name='Письмо о новых задачах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отображаемое имя'),
        ),
    ]
