# Generated by Django 4.2.26 on 2025-11-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_household_digest_user_email_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_household_invites',
            field=models.BooleanField(default=True, verbose_name='Получать письма о приглашениях в хозяйство'),
        ),
    ]
