# Generated by Django 4.2.26 on 2025-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_household_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_new_task',
        ),
        migrations.AddField(
            model_name='user',
            name='email_task_updates',
            field=models.BooleanField(default=True, verbose_name='Получать письма о новых задачах'),
        ),
    ]
