# Generated by Django 4.2.26 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_email_new_task_user_email_task_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_task_updates',
        ),
        migrations.AddField(
            model_name='user',
            name='email_new_task',
            field=models.BooleanField(default=True, verbose_name='Письмо о новых задачах'),
        ),
    ]
