# Generated by Django 4.2.26 on 2025-11-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=tasks.models.invite_generate_token, editable=False, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено'), ('EXPIRED', 'Просрочено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(default=tasks.models.invite_default_expires_at, verbose_name='Истекает')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято в')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['-created_at'], 'verbose_name': 'Хозяйство', 'verbose_name_plural': 'Хозяйства'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_households', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='household',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='household',
            name='gift',
            field=models.CharField(max_length=150, verbose_name='Подарок победителю месяца'),
        ),
        migrations.AlterField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='households', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выполнено в'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.household', verbose_name='Хозяйство'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=10, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Задача'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['household', 'is_completed'], name='tasks_task_househo_aab30e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed_at'], name='tasks_task_complet_b3d8de_idx'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tasks.household', verbose_name='Хозяйство'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Кого пригласили'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='tasks_invit_token_b22ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'expires_at'], name='tasks_invit_status_aa2288_idx'),
        ),
    ]
